### ISSUE TITLE
Classes instead of public functions

### ISSUE THREAD

**Issue by SteButler** [Xenland/BIK_php#8]
shouldn't this all be wrapped in a class? then changing currencies would be a breeze....

**Comment by Xenland** [comment]
yes it should be actually, I'm working on a website that will incorporate bitocins and litecoins together, however i won't get to litecoin integration for a while and thus won't get to update the library for a while. If anyone is willing to convert that into a class package thata be fine and dandy, and also i wouldn't mind if any "bitcoin_" function was changed to "coin_" instead if it floats your boat.
